// COMServer.idl : COMServer的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(COMServer.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(F2C3E4B8-8C7F-4194-9A87-24A0F09E471D),
	dual,
	nonextensible,
	pointer_default(unique),
	custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "MyServer.IWelcome")
]
interface IWelcome : IDispatch{
	[id(1)] HRESULT Greeting([in] BSTR name, [out, retval] BSTR* message);
};

[
	object,
	uuid(C4015DCB-E021-4A93-B4A4-C1D2BFC97108),
	dual,
	nonextensible,
	pointer_default(unique),
	custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "MyServer.IMath")
]
interface IMath : IDispatch {
	[id(1)] HRESULT Add([in] LONG val1, [in] LONG val2, [out, retval] LONG* result);
	[id(2)] HRESULT Sub([in] LONG val1,[in] LONG val2,[out,retval] LONG* result);
};

[
	uuid(C1842F49-F821-4913-8CD1-C9C663BB5EBC),
	version(1.0),
]
library COMServerLib
{
	importlib("stdole2.tlb");
	//添加连接点
	[
		uuid(1B7318A0-46CA-44A6-AA42-C91AEEA1ABEF),
		helpstring("_ICompletedEvents Interface"),
		custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "MyServer.ICompletedEvents")
	]
	dispinterface ICompletedEvents
	{
		properties:
		methods:
			[id(1)] void Completed(void);
	};




	[
		uuid(2DF6E3A6-0841-461E-9D63-05BE1634E323),
		helpstring("COMDemo Class"),
		custom(0F21F359-AB84-41E8-9A78-36D110E6D2F9, "MyServer.COMDemo")
	]
	coclass COMDemo
	{
		[default] interface IWelcome;
		interface IMath;

		[default, source] dispinterface _ICompletedEvents;

	};
};

