// HMTestCom.idl : type library source for HMTestCom.dll
// This file will be processed by the MIDL compiler to produce the
// type library (HMTestCom.tlb).

#include "olectl.h"
[uuid(29F65D2A-0E6C-41A2-8491-C68B5064EFCE), version(1.0)]
library HMTestCom
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	//  Primary dispatch interface for Test
		
	[ uuid(F6652258-E66F-40DA-9AE4-1FA1A000243A) ]
	dispinterface ITest
	{
		properties:
		methods:
			[id(1)] void HelloWorld();
	};

	//  Class information for Test

	[ uuid(8C232D31-CC22-487C-901E-C9FB883D3D74) ]
	coclass Test
	{
		[default] dispinterface ITest;
	};
};
