//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by main_application.rc
//
#define IDR_MAINFRAME                   127
#define IDD_ABOUTBOX                    130
#define IDP_OLE_INIT_FAILED             131
#define ID_MENU_NEW_COMPONENT           133
#define ID_MENU_DELETE_COMPONENT        134
#define IDS_RIBBON_UI_OTHERS            135
#define IDR_RIBBON_MENU                 136
#define IDR_POPUP_EXPLORER              137
#define ID_RIBBON_MENU_UNDO             145
#define ID_RIBBON_MENU_REDO             146
#define ID_RIBBON_MENU_FILE_NEW         147
#define ID_RIBBON_MENU_FILE_OPEN        148
#define ID_RIBBON_MENU_FILE_SAVE        149
#define ID_RIBBON_MENU_FILE_SAVE_AS     150
#define ID_RIBBON_MENU_FILE_SAVE_AS_TEMPLATE 151
#define ID_RIBBON_MENU_SAVE_PACKAGE     152
#define ID_RIBBON_MENU_FILE_CLOSE       153
#define ID_RIBBON_MENU_TAB_CLOSE        154
#define ID_RIBBON_MENU_START_PAGE       156
#define ID_RIBBON_MENU_CALC_ALL_MODELS  158
#define ID_RIBBON_MENU_FILE_PRINT       170
#define ID_RIBBON_MENU_FILE_PRINT_PREVIEW 171
#define ID_RIBBON_MENU_FILE_PRINT_SETTING 172
#define ID_APP_OPTIONS                  183
#define ID_FILE_RECENTDOCUMENTS         184
#define ID_THEME_STYLEBLUE2007          301
#define ID_THEME_STYLESILVER2007        302
#define ID_THEME_STYLEBLACK2007         303
#define ID_THEME_STYLEBLUE2010          304
#define ID_THEME_STYLESILVER2010        305
#define ID_THEME_STYLEBLACK2010         306
#define ID_THEME_STYLE_LIGHT2013        307
#define ID_THEME_STYLE_DARK2013         308
#define IDR_MENU_OPTIONS                315
#define IDR_MENU_WORKSPACE_TAB          510
#define ID_WORKSPACETABPOPUPMENU_SAVE   10001
#define ID_WORKSPACETABPOPUPMENU_CLOSE  10002
#define ID_WORKSPACETABPOPUPMENU_CLOSE_ALL 10003
#define ID_WORKSPACETABPOPUPMENU_SAVE_ALL 10004

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        516
#define _APS_NEXT_COMMAND_VALUE         10007
#define _APS_NEXT_CONTROL_VALUE         3004
#define _APS_NEXT_SYMED_VALUE           510
#endif
#endif
